/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-18 03:32:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dnav_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"pcoded-navbar  \">\n");
      out.write("	<div class=\"navbar-wrapper  \">\n");
      out.write("		<div class=\"navbar-content scroll-div \">\n");
      out.write("\n");
      out.write("			<div class=\"\">\n");
      out.write("				<div class=\"main-menu-header\">\n");
      out.write("					<img class=\"img-radius\" src=\"assets/images/user/avatar-default.png\" alt=\"User-Profile-Image\">\n");
      out.write("					<div class=\"user-details\">\n");
      out.write("						<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</span>\n");
      out.write("						<div id=\"more-details\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${role}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("<i class=\"fa fa-chevron-down m-l-5\"></i>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"collapse\" id=\"nav-user-link\">\n");
      out.write("					<ul class=\"list-unstyled\">\n");
      out.write("						<li class=\"list-group-item\"><a href=\"logout.do\"><i class=\"feather icon-log-out m-r-5\"></i>Logout</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<ul class=\"nav pcoded-inner-navbar \">\n");
      out.write("				<li class=\"nav-item pcoded-menu-caption\"><label>요약</label></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"adminMain.do\" class=\"nav-link \"><span class=\"pcoded-micon\"><i class=\"feather icon-home\"></i></span><span class=\"pcoded-mtext\">대시보드</span></a></li>\n");
      out.write("				<li class=\"nav-item pcoded-menu-caption\"><label>상품</label></li>\n");
      out.write("				<li class=\"nav-item pcoded-hasmenu\"><a href=\"#!\" class=\"nav-link \"><span class=\"pcoded-micon\"><i class=\"feather icon-box\"></i></span><span class=\"pcoded-mtext\">제품 관리</span></a>\n");
      out.write("					<ul class=\"pcoded-submenu\">\n");
      out.write("						<li><a href=\"productListPage.do\">제품 목록</a></li>\n");
      out.write("						<li><a href=\"addProductPage.do\">제품 등록</a></li>\n");
      out.write("						<li><a href=\"categoryListPage.do\">카테고리 관리</a></li>\n");
      out.write("						<li><a href=\"addImageDataPage.do\">더미데이터 사진 추가</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("				<li class=\"nav-item pcoded-menu-caption\"><label>주문</label></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"orderListPage.do\" class=\"nav-link \"><span class=\"pcoded-micon\"><i class=\"feather icon-pie-chart\"></i></span><span class=\"pcoded-mtext\">주문 내역</span></a></li>\n");
      out.write("				<li class=\"nav-item pcoded-hasmenu\"><a href=\"#!\" class=\"nav-link \"><span class=\"pcoded-micon\"><i class=\"feather icon-edit\"></i></span><span class=\"pcoded-mtext\">리뷰 관리</span></a>\n");
      out.write("					<ul class=\"pcoded-submenu\">\n");
      out.write("						<li><a href=\"reviewPage.do\">리뷰 내역</a></li>\n");
      out.write("						<li><a href=\"addreviewPage.do\">리뷰 등록</a></li>\n");
      out.write("					</ul></li>\n");
      out.write("				<li class=\"nav-item pcoded-menu-caption\"><label>회원</label></li>\n");
      out.write("				<li class=\"nav-item\"><a href=\"memberListPage.do\" class=\"nav-link \"><span class=\"pcoded-micon\"><i class=\"feather icon-user\"></i></span><span class=\"pcoded-mtext\">회원 관리</span></a></li>\n");
      out.write("			</ul>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</nav>\n");
      out.write("<!-- [ Header ] start -->\n");
      out.write("<header class=\"navbar pcoded-header navbar-expand-lg navbar-light header-dark\">\n");
      out.write("	<div class=\"m-header\">\n");
      out.write("		<a class=\"mobile-menu\" id=\"mobile-collapse\" href=\"#!\"><span></span></a>\n");
      out.write("		<a href=\"adminMain.do\" class=\"b-brand\">\n");
      out.write("			<img class=\"wid-20\" src=\"assets/images/logo-no-background.png\" alt=\"\" class=\"logo\">\n");
      out.write("			<span class=\"m-l-10\">&nbsp;SoundPlay</span>\n");
      out.write("		</a> <a href=\"#!\" class=\"mob-toggler\"> <i class=\"feather icon-more-vertical\"></i>\n");
      out.write("		</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"collapse navbar-collapse\">\n");
      out.write("		<ul class=\"navbar-nav mr-auto\">\n");
      out.write("			<li class=\"nav-item\"><a href=\"#!\" class=\"pop-search\"><i class=\"feather icon-search\"></i></a>\n");
      out.write("				<div class=\"search-bar\">\n");
      out.write("					<input type=\"text\" class=\"form-control border-0 shadow-none\" placeholder=\"Search hear\">\n");
      out.write("					<button type=\"button\" class=\"close\" aria-label=\"Close\">\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</button>\n");
      out.write("				</div></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("</header>\n");
      out.write("<!-- [ Header ] end -->");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
