/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-15 02:05:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/WEB-INF/tags/header.tag", Long.valueOf(1693804315153L));
    _jspx_dependants.put("/WEB-INF/tags/footer.tag", Long.valueOf(1693119357501L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1691645570010L));
    _jspx_dependants.put("/WEB-INF/tags/recProduct.tag", Long.valueOf(1693787781283L));
    _jspx_dependants.put("/WEB-INF/tags/chatBot.tag", Long.valueOf(1694417783798L));
    _jspx_dependants.put("jar:file:/D:/lee/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/chatSLK_final_01/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/tags/modal.tag", Long.valueOf(1693119401401L));
    _jspx_dependants.put("/WEB-INF/tags/recCategory.tag", Long.valueOf(1693803510665L));
    _jspx_dependants.put("/WEB-INF/tags/nav.tag", Long.valueOf(1693119404160L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>SoundPlay - 사운드플레이, 스피커의 모든 것</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/adminstyle.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/logo-no-background.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"assets/css/swiper.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\" />\r\n");
      out.write("<!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Top Nav -->\r\n");
      out.write("	");
      if (_jspx_meth_slk_005fnav_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- Close Top Nav -->\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	");
      if (_jspx_meth_slk_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	");
      if (_jspx_meth_slk_005fmodal_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 챗봇 -->\r\n");
      out.write("	");
      if (_jspx_meth_slk_005fchatBot_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Banner Hero -->\r\n");
      out.write("	<!-- 여기에 slick slider 들어가면 됩니다 -->\r\n");
      out.write("	<section class=\"container py-5\">\r\n");
      out.write("		<div class=\"swiper mySwiper\">\r\n");
      out.write("			<div class=\"swiper-wrapper\">\r\n");
      out.write("				<div class=\"swiper-slide\">\r\n");
      out.write("					<img alt=\"이미지1\" src=\"./assets/img/test/contrast-Standard.jpg\" width=100%>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"swiper-slide\">\r\n");
      out.write("					<img alt=\"이미지2\" src=\"./assets/img/test/kj6h5rg.jpg\" width=100%>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"swiper-slide\">\r\n");
      out.write("					<img alt=\"이미지3\" src=\"./assets/img/test/cms105.jpg\" width=100%>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"swiper-button-prev\" style=\"color: #eeeeee !important; padding-left: 50px;\"></div>\r\n");
      out.write("		<div class=\"swiper-button-next\" style=\"color: #eeeeee !important; padding-right: 50px;\"></div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Categories of The Month -->\r\n");
      out.write("	<section class=\"container py-5\">\r\n");
      out.write("		<div class=\"row text-center pt-3\">\r\n");
      out.write("			<div class=\"col-lg-6 m-auto\">\r\n");
      out.write("				<h1 class=\"h1\">추천 카테고리</h1>\r\n");
      out.write("				<p>&nbsp;</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");
      if (_jspx_meth_slk_005frecCategory_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Categories of The Month -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Featured Product -->\r\n");
      out.write("	<section class=\"bg-light\" style=\"background-color: #eeeeee !important;\">\r\n");
      out.write("		<div class=\"container py-5\">\r\n");
      out.write("			<div class=\"row text-center py-3\">\r\n");
      out.write("				<div class=\"col-lg-6 m-auto\">\r\n");
      out.write("					<h1 class=\"h1\">추천 상품</h1>\r\n");
      out.write("					<p>&nbsp;</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");
      if (_jspx_meth_slk_005frecProduct_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Featured Product -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_slk_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Script -->\r\n");
      out.write("	<script src=\"assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/templatemo.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/swiper.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	//페이지 로드 후 실행\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("	    // 각 별점에 대한 처리\r\n");
      out.write("	    const productStars = document.querySelectorAll('[class^=\"productstar\"]');\r\n");
      out.write("	    productStars.forEach(starContainer => {\r\n");
      out.write("	        const starCount = parseInt(starContainer.classList[0].replace(\"productstar\", \"\"));\r\n");
      out.write("	        for (let i = 0; i < 5; i++) {\r\n");
      out.write("	            const starIcon = document.createElement(\"i\");\r\n");
      out.write("	            starIcon.classList.add(\"text-warning\", \"fa\", \"fa-star\");\r\n");
      out.write("	            if (i >= starCount) {\r\n");
      out.write("	                starIcon.classList.remove(\"text-warning\");\r\n");
      out.write("	                starIcon.classList.add(\"text-muted\", \"fa\", \"fa-star\");\r\n");
      out.write("	            }\r\n");
      out.write("	            starContainer.appendChild(document.createTextNode(\"\\n\")); // 줄바꿈\r\n");
      out.write("	            starContainer.appendChild(starIcon);\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_slk_005fnav_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:nav
    org.apache.jsp.tag.web.nav_tag _jspx_th_slk_005fnav_005f0 = new org.apache.jsp.tag.web.nav_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005fnav_005f0);
    try {
      _jspx_th_slk_005fnav_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005fnav_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005fnav_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_slk_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:header
    org.apache.jsp.tag.web.header_tag _jspx_th_slk_005fheader_005f0 = new org.apache.jsp.tag.web.header_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005fheader_005f0);
    try {
      _jspx_th_slk_005fheader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005fheader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005fheader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_slk_005fmodal_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:modal
    org.apache.jsp.tag.web.modal_tag _jspx_th_slk_005fmodal_005f0 = new org.apache.jsp.tag.web.modal_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005fmodal_005f0);
    try {
      _jspx_th_slk_005fmodal_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005fmodal_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005fmodal_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_slk_005fchatBot_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:chatBot
    org.apache.jsp.tag.web.chatBot_tag _jspx_th_slk_005fchatBot_005f0 = new org.apache.jsp.tag.web.chatBot_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005fchatBot_005f0);
    try {
      _jspx_th_slk_005fchatBot_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005fchatBot_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005fchatBot_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_slk_005frecCategory_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:recCategory
    org.apache.jsp.tag.web.recCategory_tag _jspx_th_slk_005frecCategory_005f0 = new org.apache.jsp.tag.web.recCategory_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005frecCategory_005f0);
    try {
      _jspx_th_slk_005frecCategory_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005frecCategory_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005frecCategory_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_slk_005frecProduct_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:recProduct
    org.apache.jsp.tag.web.recProduct_tag _jspx_th_slk_005frecProduct_005f0 = new org.apache.jsp.tag.web.recProduct_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005frecProduct_005f0);
    try {
      _jspx_th_slk_005frecProduct_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005frecProduct_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005frecProduct_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_slk_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  slk:footer
    org.apache.jsp.tag.web.footer_tag _jspx_th_slk_005ffooter_005f0 = new org.apache.jsp.tag.web.footer_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_slk_005ffooter_005f0);
    try {
      _jspx_th_slk_005ffooter_005f0.setJspContext(_jspx_page_context);
      _jspx_th_slk_005ffooter_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_slk_005ffooter_005f0);
    }
    return false;
  }
}
